name: CI/CD

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        language: [javascript]


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install


    - name: Build
      run: npm run build
      
  code_scanning:
    name: Code Scanning
    strategy:
      matrix:
        language: [javascript]     
    runs-on: ubuntu-latest 
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
         languages: ${{ matrix.language }}
     
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      
  
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build,code_scanning]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:latest
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-image-name:latest'
          format: 'template'
          exit-code: '0'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'

      
  push_to_registry:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build,build_docker_image,code_scanning]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker image ls
