name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install


    - name: Build
      run: npm run build
  
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:latest
 
  scanning_docker_Image:
    name: Security Scan for Docker Image
    runs-on: ubuntu-latest
    needs: [build,build_docker_image]
    steps:
      - uses: azure/container-scan@v0
        with:
          image-name: my-image-name:latest
    
      
  push_to_registry:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build,build_docker_image,scanning_docker_Image]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: docker image ls
